import SwiftUI

private struct PersonalCourse: Identifiable { let id=UUID(); var title:String; var description:String; var sections:[CourseSection]=[]; var goals:[CourseGoal]=[] }
private struct CourseSection: Identifiable { let id=UUID(); var title:String; var topics:[CourseTopic]=[] }
private struct CourseTopic: Identifiable { let id=UUID(); var title:String; var rules:[RuleRef]=[] }
private struct RuleRef: Identifiable, Hashable { let materialID:UUID; let ruleID:UUID; var id:String { "\(materialID)-\(ruleID)" } }
private struct CourseGoal: Identifiable { let id=UUID(); var title:String; var rules:[RuleRef]; var mastery:Int }

struct CoursesView: View {
 @Environment(\.dismiss) private var dismiss; @State private var courses:[PersonalCourse]=[]; @State private var create=false
 var body:some View { NavigationStack { ZStack { CourseBackground(); ScrollView { VStack(spacing:18) { intro; if courses.isEmpty { empty } else { ForEach($courses){$course in NavigationLink{CourseEditorView(course:$course)}label:{CourseCard(course:course)}.buttonStyle(.plain)} } }.padding(16) } }.navigationTitle("Мои курсы").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement:.topBarLeading){Button("Закрыть"){dismiss()}}; ToolbarItem(placement:.topBarTrailing){Button{create=true}label:{Image(systemName:"plus.circle.fill").font(.title2)}} }.sheet(isPresented:$create){NewCourseView{courses.append(.init(title:$0,description:$1))}} } }
 private var intro:some View { VStack(alignment:.leading,spacing:8){Text("СОБЕРИ СВОЮ ПРОГРАММУ").font(.caption.bold()).foregroundStyle(.cyan);Text("Разделы → темы → опросники").font(.title2.bold()).foregroundStyle(.white);Text("Сначала собери содержание курса. Потом составь из его опросников последовательность целей.").font(.subheadline).foregroundStyle(.white.opacity(0.65))}.frame(maxWidth:.infinity,alignment:.leading).padding(16).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:20)).overlay(RoundedRectangle(cornerRadius:20).stroke(.cyan.opacity(0.2))) }
 private var empty:some View { Button{create=true}label:{VStack(spacing:12){Image(systemName:"square.stack.3d.up.fill").font(.system(size:38));Text("Создать первый курс").font(.headline);Text("Например: ЕГЭ Химия 2027").font(.caption).opacity(0.65)}.frame(maxWidth:.infinity).padding(.vertical,38)}.buttonStyle(.borderedProminent).tint(.cyan.opacity(0.28)).foregroundStyle(.white) }
}
private struct CourseCard:View { let course:PersonalCourse; var body:some View { HStack(spacing:14){Image(systemName:"square.stack.3d.up.fill").font(.title2).foregroundStyle(.cyan);VStack(alignment:.leading,spacing:5){Text(course.title).font(.headline);if !course.description.isEmpty{Text(course.description).font(.caption).foregroundStyle(.white.opacity(0.6))};Text("\(course.sections.count) разделов · \(course.sections.flatMap(\.topics).count) тем · \(course.goals.count) целей").font(.caption2).foregroundStyle(.cyan)};Spacer();Image(systemName:"chevron.right")}.foregroundStyle(.white).padding(16).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(.cyan.opacity(0.22))) } }
private struct NewCourseView:View { @Environment(\.dismiss)var dismiss;@State var title="";@State var desc="";let save:(String,String)->Void;var body:some View{NavigationStack{ZStack{CourseBackground();VStack(spacing:16){editorField("НАЗВАНИЕ КУРСА","Например: ЕГЭ Химия",$title);editorField("ОПИСАНИЕ","Необязательно",$desc);Spacer()}.padding(18)}.navigationTitle("Новый курс").toolbar{ToolbarItem(placement:.cancellationAction){Button("Отмена"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Создать"){save(title.trimmed,desc);dismiss()}.disabled(title.trimmed.isEmpty)}}}} }

private struct CourseEditorView:View {
 @Binding var course:PersonalCourse;@State private var tab=0;@State private var addSection=false;@State private var addGoal=false
 var body:some View{ZStack{CourseBackground();VStack(spacing:12){Picker("",selection:$tab){Text("Содержание").tag(0);Text("Цели").tag(1)}.pickerStyle(.segmented).padding(.horizontal,16);if tab==0{structure}else{goals}}}.navigationTitle(course.title).navigationBarTitleDisplayMode(.inline).sheet(isPresented:$addSection){NameSheet(title:"Новый раздел",placeholder:"Например: Неорганическая химия"){course.sections.append(.init(title:$0))}}.sheet(isPresented:$addGoal){GoalEditorSheet(course:course){course.goals.append($0)}}}
 private var structure:some View{ScrollView{LazyVStack(spacing:14){ForEach(Array(course.sections.enumerated()),id:\.element.id){index,_ in SectionCard(section:$course.sections[index],number:index+1)};Button{addSection=true}label:{Label("Добавить раздел",systemImage:"plus.circle.fill").frame(maxWidth:.infinity).padding(12)}.buttonStyle(.borderedProminent).tint(.cyan.opacity(0.28))}.padding(16)}}
 private var goals:some View{ScrollView{VStack(alignment:.leading,spacing:12){Text("МОЯ ПОСЛЕДОВАТЕЛЬНОСТЬ").font(.caption.bold()).foregroundStyle(.cyan);Text("Цели идут сверху вниз. В самостоятельном курсе это твой план: любую цель можно будет поставить на паузу и перейти к другой.").font(.caption).foregroundStyle(.white.opacity(0.6));ForEach(Array(course.goals.enumerated()),id:\.element.id){i,g in HStack{Text("\(i+1)").font(.title3.bold()).foregroundStyle(.cyan).frame(width:30);VStack(alignment:.leading){Text(g.title).font(.headline);Text("\(g.rules.count) опросников · освоить \(g.mastery)%").font(.caption).foregroundStyle(.white.opacity(0.55))};Spacer();Image(systemName:"line.3.horizontal").foregroundStyle(.white.opacity(0.35))}.foregroundStyle(.white).padding(14).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:16))};Button{addGoal=true}label:{Label("Добавить цель",systemImage:"plus.circle.fill").frame(maxWidth:.infinity).padding(10)}.buttonStyle(.borderedProminent).tint(.cyan.opacity(0.28))}.padding(16)}}
}
private struct SectionCard:View { @Binding var section:CourseSection;let number:Int;@State var addTopic=false;var body:some View{VStack(alignment:.leading,spacing:12){HStack(alignment:.center){Text("\(number)").font(.headline).foregroundStyle(.black).frame(width:30,height:30).background(.cyan,in:Circle());TextField("Название раздела",text:$section.title).font(.headline).foregroundStyle(.white);Spacer();Image(systemName:"line.3.horizontal").foregroundStyle(.white.opacity(0.35))};if section.topics.isEmpty{Text("Добавь темы этого раздела").font(.caption).foregroundStyle(.white.opacity(0.45)).padding(.leading,42)};ForEach(Array(section.topics.enumerated()),id:\.element.id){i,_ in NavigationLink{TopicEditorView(topic:$section.topics[i])}label:{HStack{VStack(alignment:.leading,spacing:3){Text(section.topics[i].title).font(.subheadline.bold());Text("\(section.topics[i].rules.count) опросников").font(.caption2).foregroundStyle(.cyan)};Spacer();Image(systemName:"chevron.right")}.foregroundStyle(.white).padding(12).background(.black.opacity(0.24),in:RoundedRectangle(cornerRadius:13))}};Button{addTopic=true}label:{Label("Добавить тему",systemImage:"plus").font(.subheadline.bold()).foregroundStyle(.cyan)}}.padding(14).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(.cyan.opacity(0.18))).sheet(isPresented:$addTopic){NameSheet(title:"Новая тема",placeholder:"Например: Кислоты"){section.topics.append(.init(title:$0))}}} }
private struct TopicEditorView:View { @Environment(MaterialStore.self) var materials;@Binding var topic:CourseTopic;@State var choose=false;var body:some View{ZStack{CourseBackground();ScrollView{VStack(alignment:.leading,spacing:16){editorField("НАЗВАНИЕ ТЕМЫ","Например: Кислоты",$topic.title);VStack(alignment:.leading,spacing:10){Text("ПРИВЯЗАННЫЕ ОПРОСНИКИ").font(.caption.bold()).foregroundStyle(.cyan);if topic.rules.isEmpty{Text("Пока ничего не выбрано. Нажми кнопку ниже и выбери конкретные наборы вопросов из своих материалов.").font(.subheadline).foregroundStyle(.white.opacity(0.6))}else{ForEach(topic.rules){ref in if let x=ruleInfo(ref,materials){HStack{Image(systemName:"questionmark.bubble.fill").foregroundStyle(.mint);VStack(alignment:.leading){Text(x.0).foregroundStyle(.white);Text(x.1).font(.caption).foregroundStyle(.cyan)}}.padding(11).background(.black.opacity(0.25),in:RoundedRectangle(cornerRadius:12))}}};Button{choose=true}label:{Label(topic.rules.isEmpty ? "Выбрать опросники":"Изменить опросники",systemImage:"checklist").frame(maxWidth:.infinity).padding(10)}.buttonStyle(.borderedProminent).tint(.cyan.opacity(0.3))}.padding(15).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18))}.padding(16)}}.navigationTitle("Тема").navigationBarTitleDisplayMode(.inline).sheet(isPresented:$choose){RulePicker(selected:$topic.rules)}} }

private struct RulePicker:View { @Environment(MaterialStore.self)var materials;@Environment(\.dismiss)var dismiss;@Binding var selected:[RuleRef];var body:some View{NavigationStack{ZStack{CourseBackground();ScrollView{LazyVStack(spacing:12){if materials.materials.isEmpty{ContentUnavailableView("Нет материалов",systemImage:"books.vertical",description:Text("Сначала добавь материал с наборами вопросов в библиотеку."))}else{ForEach(materials.materials){m in if let c=materials.content(id:m.id),!c.rules.isEmpty{VStack(alignment:.leading,spacing:8){Text(m.title).font(.headline).foregroundStyle(.white);Text("Выбери наборы вопросов").font(.caption).foregroundStyle(.white.opacity(0.5));ForEach(c.rules.filter(\.enabled)){rule in let ref=RuleRef(materialID:m.id,ruleID:rule.id);Button{toggle(ref)}label:{HStack(alignment:.top){Image(systemName:selected.contains(ref) ? "checkmark.circle.fill":"circle").foregroundStyle(selected.contains(ref) ? .cyan:.white.opacity(0.4));VStack(alignment:.leading,spacing:3){Text(ruleName(rule,c)).foregroundStyle(.white);Text("\(c.rows.count) вопросов").font(.caption2).foregroundStyle(.white.opacity(0.45))};Spacer()}.padding(10).background(.black.opacity(0.22),in:RoundedRectangle(cornerRadius:12))}.buttonStyle(.plain)}}.padding(14).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18))}}}}.padding(16)}}.navigationTitle("Выбрать опросники").toolbar{Button("Готово"){dismiss()}}}};private func toggle(_ r:RuleRef){if let i=selected.firstIndex(of:r){selected.remove(at:i)}else{selected.append(r)}} }

private struct GoalEditorSheet:View { @Environment(\.dismiss)var dismiss;@Environment(MaterialStore.self)var materials;let course:PersonalCourse;let save:(CourseGoal)->Void;@State var title="";@State var mastery=85;@State var selected:[RuleRef]=[];@State var choose=false;var body:some View{NavigationStack{ZStack{CourseBackground();ScrollView{VStack(spacing:16){editorField("НАЗВАНИЕ ЦЕЛИ","Например: Выучить основные кислоты",$title);VStack(alignment:.leading,spacing:8){Text("ЧТО УЧИТЬ").font(.caption.bold()).foregroundStyle(.cyan);Text(selected.isEmpty ? "Опросники не выбраны":"Выбрано: \(selected.count)").foregroundStyle(.white);Button("Выбрать опросники"){choose=true}.buttonStyle(.borderedProminent).tint(.cyan.opacity(0.3))}.frame(maxWidth:.infinity,alignment:.leading).padding(15).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18));VStack(alignment:.leading,spacing:8){Text("КРИТЕРИЙ ВЫПОЛНЕНИЯ").font(.caption.bold()).foregroundStyle(.cyan);Stepper("Освоить \(mastery)%",value:$mastery,in:50...100,step:5).foregroundStyle(.white)}.padding(15).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18))}.padding(16)}}.navigationTitle("Новая цель").toolbar{ToolbarItem(placement:.cancellationAction){Button("Отмена"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Добавить"){save(.init(title:title.trimmed,rules:selected,mastery:mastery));dismiss()}.disabled(title.trimmed.isEmpty||selected.isEmpty)}}.sheet(isPresented:$choose){RulePicker(selected:$selected)}}} }
private struct NameSheet:View{@Environment(\.dismiss)var dismiss;let title:String;let placeholder:String;let save:(String)->Void;@State var value="";var body:some View{NavigationStack{ZStack{CourseBackground();VStack{editorField("НАЗВАНИЕ",placeholder,$value);Spacer()}.padding(18)}.navigationTitle(title).toolbar{ToolbarItem(placement:.cancellationAction){Button("Отмена"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Добавить"){save(value.trimmed);dismiss()}.disabled(value.trimmed.isEmpty)}}}}}
private func editorField(_ label:String,_ placeholder:String,_ value:Binding<String>)->some View{VStack(alignment:.leading,spacing:7){Text(label).font(.caption.bold()).foregroundStyle(.cyan);TextField(placeholder,text:value,axis:.vertical).foregroundStyle(.white).padding(13).background(.black.opacity(0.28),in:RoundedRectangle(cornerRadius:13)).overlay(RoundedRectangle(cornerRadius:13).stroke(.cyan.opacity(0.18)))}.frame(maxWidth:.infinity,alignment:.leading)}
@MainActor private func ruleInfo(_ ref:RuleRef,_ store:MaterialStore)->(String,String)?{guard let c=store.content(id:ref.materialID),let r=c.rules.first(where:{$0.id==ref.ruleID})else{return nil};return (c.material.title,ruleName(r,c))}
private func ruleName(_ r:QuestionRule,_ c:MaterialContent)->String{let fields=Dictionary(uniqueKeysWithValues:c.fields.map{($0.key,$0.title)});let from=r.promptFieldKeys.compactMap{fields[$0]}.joined(separator:" + ");let answerKeys=Array(Set(r.answers.flatMap(\.fieldKeys)+[r.answerFieldKey])).filter{!$0.isEmpty};let to=answerKeys.compactMap{fields[$0]}.joined(separator:" + ");if !from.isEmpty && !to.isEmpty{return "\(from) → \(to)"};return r.kind == .card ? "Карточки":"Выбор ответа"}
private struct CourseBackground:View{var body:some View{LinearGradient(colors:[Color(red:0.015,green:0.035,blue:0.12),Color(red:0.03,green:0.08,blue:0.18),.black],startPoint:.top,endPoint:.bottom).ignoresSafeArea()}}
private extension String{var trimmed:String{trimmingCharacters(in:.whitespacesAndNewlines)}}
