import SwiftUI

private struct PersonalCourse: Identifiable { let id=UUID(); var title:String; var description:String; var sections:[CourseSection]=[]; var goals:[CourseGoal]=[] }
private struct CourseSection: Identifiable { let id=UUID(); var title:String; var topics:[CourseTopic]=[] }
private struct CourseTopic: Identifiable { let id=UUID(); var title:String; var quizIDs:Set<UUID>=[] }
private struct CourseGoal: Identifiable { let id=UUID(); var title:String; var quizIDs:Set<UUID>; var mastery:Int; var state:GoalState = .planned }
private enum GoalState { case planned, active, paused, completed }

struct CoursesView: View {
 @Environment(\.dismiss) private var dismiss; @State private var courses:[PersonalCourse]=[]; @State private var create=false
 var body:some View { NavigationStack { ZStack { CourseBackground(); Group { if courses.isEmpty { ContentUnavailableView("Создай свой курс",systemImage:"square.stack.3d.up",description:Text("Собери структуру из разделов и тем, привяжи свои опросники и составь последовательность целей.")) } else { ScrollView { VStack(spacing:12) { ForEach($courses) { $course in NavigationLink { CourseEditorView(course:$course) } label:{ CourseCard(course:course) }.buttonStyle(.plain) } }.padding(16) } } } }.navigationTitle("Мои курсы").toolbar { ToolbarItem(placement:.topBarLeading){Button("Готово"){dismiss()}};ToolbarItem(placement:.topBarTrailing){Button{create=true}label:{Image(systemName:"plus")}} }.sheet(isPresented:$create){NewCourseView{title,desc in courses.append(.init(title:title,description:desc))}} } }
}
private struct CourseCard:View { let course:PersonalCourse; var body:some View { HStack { VStack(alignment:.leading,spacing:5){Text(course.title).font(.headline);if !course.description.isEmpty{Text(course.description).font(.caption).foregroundStyle(.white.opacity(0.6))};Text("\(course.sections.count) разделов · \(course.goals.count) целей").font(.caption2).foregroundStyle(.cyan)};Spacer();Image(systemName:"chevron.right")}.foregroundStyle(.white).padding(16).background(.black.opacity(0.3),in:RoundedRectangle(cornerRadius:20)).overlay(RoundedRectangle(cornerRadius:20).stroke(.cyan.opacity(0.3))) } }
private struct NewCourseView:View { @Environment(\.dismiss) var dismiss;@State var title="";@State var desc="";let save:(String,String)->Void;var body:some View{NavigationStack{Form{Section("Новый курс"){TextField("Название",text:$title);TextField("Описание (необязательно)",text:$desc,axis:.vertical)}}.navigationTitle("Создать курс").toolbar{ToolbarItem(placement:.cancellationAction){Button("Отмена"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Создать"){save(title.trimmingCharacters(in:.whitespacesAndNewlines),desc);dismiss()}.disabled(title.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty)}}}}}

private struct CourseEditorView:View {
 @Binding var course:PersonalCourse;@State private var tab=0;@State private var newSection=false;@State private var newGoal=false
 var body:some View{ZStack{CourseBackground();VStack(spacing:10){Picker("",selection:$tab){Text("Содержание").tag(0);Text("Цели").tag(1)}.pickerStyle(.segmented).padding(.horizontal);if tab==0{content}else{goals}}}.navigationTitle(course.title).navigationBarTitleDisplayMode(.inline).sheet(isPresented:$newSection){NameSheet(title:"Новый раздел",placeholder:"Например: Неорганическая химия"){course.sections.append(.init(title:$0))}}.sheet(isPresented:$newGoal){GoalEditorSheet(course:course){course.goals.append($0)}}}
 private var content:some View{List{ForEach($course.sections){$section in Section{ForEach($section.topics){$topic in NavigationLink{TopicEditorView(topic:$topic)}label:{VStack(alignment:.leading){Text(topic.title);Text("\(topic.quizIDs.count) опросников").font(.caption).foregroundStyle(.secondary)}}}.onMove{section.topics.move(fromOffsets:$0,toOffset:$1)};Button{section.topics.append(.init(title:"Новая тема"))}label:{Label("Добавить тему",systemImage:"plus")}}header:{HStack{TextField("Раздел",text:$section.title);Spacer()}}}.onMove{course.sections.move(fromOffsets:$0,toOffset:$1)};Button{newSection=true}label:{Label("Добавить раздел",systemImage:"plus.circle.fill")}}.scrollContentBackground(.hidden).environment(\.editMode,.constant(.active))}
 private var goals:some View{List{if course.goals.isEmpty{Text("Добавь цели и расставь их в желаемой последовательности.").foregroundStyle(.secondary)};ForEach(Array(course.goals.enumerated()),id:\.element.id){index,g in HStack(spacing:12){Text("\(index+1)").font(.headline).foregroundStyle(.cyan).frame(width:28);VStack(alignment:.leading){Text(g.title);Text("\(g.quizIDs.count) опросников · освоить \(g.mastery)%").font(.caption).foregroundStyle(.secondary)}}}.onMove{course.goals.move(fromOffsets:$0,toOffset:$1)};Button{newGoal=true}label:{Label("Добавить цель",systemImage:"plus.circle.fill")}}.scrollContentBackground(.hidden).environment(\.editMode,.constant(.active))}
}
private struct TopicEditorView:View { @Binding var topic:CourseTopic;@State private var choose=false;var body:some View{Form{Section("Тема"){TextField("Название",text:$topic.title)};Section("Опросники"){if topic.quizIDs.isEmpty{Text("Опросники ещё не привязаны").foregroundStyle(.secondary)}else{Text("Выбрано: \(topic.quizIDs.count)")};Button("Выбрать опросники"){choose=true}}}.navigationTitle("Тема").sheet(isPresented:$choose){QuizPicker(selected:$topic.quizIDs)}} }
private struct QuizPicker:View { @Environment(\.dismiss) var dismiss;@Binding var selected:Set<UUID>;@State private var store=MyQuizzesStore();var body:some View{NavigationStack{Group{if store.quizzes.isEmpty{ContentUnavailableView("Нет доступных опросников",systemImage:"rectangle.stack",description:Text("Сначала создай опросник в библиотеке."))}else{List(store.quizzes){q in Button{if selected.contains(q.id){selected.remove(q.id)}else{selected.insert(q.id)}}label:{HStack{Image(systemName:selected.contains(q.id) ? "checkmark.circle.fill":"circle");Text(q.title);Spacer()}}}}}.navigationTitle("Опросники").toolbar{Button("Готово"){dismiss()}}.task{await store.refresh()}}} }
private struct GoalEditorSheet:View { @Environment(\.dismiss) var dismiss;let course:PersonalCourse;let save:(CourseGoal)->Void;@State var title="";@State var mastery=85;@State var quizzes:Set<UUID>=[];@State var choose=false;var body:some View{NavigationStack{Form{Section("Цель"){TextField("Например: выучить основные кислоты",text:$title)};Section("Что учить"){Text("Выбрано опросников: \(quizzes.count)");Button("Выбрать опросники"){choose=true}};Section("Когда считать выполненной"){Stepper("Освоить \(mastery)%",value:$mastery,in:50...100,step:5)}}.navigationTitle("Новая цель").toolbar{ToolbarItem(placement:.cancellationAction){Button("Отмена"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Добавить"){save(.init(title:title.trimmingCharacters(in:.whitespacesAndNewlines),quizIDs:quizzes,mastery:mastery));dismiss()}.disabled(title.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty || quizzes.isEmpty)}}.sheet(isPresented:$choose){QuizPicker(selected:$quizzes)}}} }
private struct NameSheet:View{@Environment(\.dismiss)var dismiss;let title:String;let placeholder:String;let save:(String)->Void;@State var value="";var body:some View{NavigationStack{Form{TextField(placeholder,text:$value)}.navigationTitle(title).toolbar{ToolbarItem(placement:.cancellationAction){Button("Отмена"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Добавить"){save(value.trimmingCharacters(in:.whitespacesAndNewlines));dismiss()}.disabled(value.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty)}}}}}
private struct CourseBackground:View{var body:some View{LinearGradient(colors:[Color(red:0.015,green:0.035,blue:0.12),Color(red:0.03,green:0.08,blue:0.18),.black],startPoint:.top,endPoint:.bottom).ignoresSafeArea()}}
