import SwiftUI
struct GameHomeView: View {
 @Environment(LearningStore.self) private var store; @State private var learn=false; @State private var profile=false; @State private var chooser=false; @State private var botanOpen=false
 private let plans=MVPDemoData.plans
 var body:some View { NavigationStack { ZStack(alignment:.bottomTrailing){ DigitalBackground(); VStack(spacing:10){topBar; motivation; goalStrip; forecast; recommendation; Spacer(minLength:6); actions}.padding(.horizontal,14).padding(.bottom,12); Button{botanOpen=true}label:{BotanRobot().frame(width:112,height:124).shadow(color:.cyan.opacity(0.35),radius:16)}.buttonStyle(.plain).padding(.trailing,6).padding(.bottom,78) }.toolbar(.hidden,for:.navigationBar).sheet(isPresented:$learn){LearnSessionView()}.sheet(isPresented:$profile){NavigationStack{ProfileView()}}.sheet(isPresented:$chooser){MixChooserView(start:{q in store.use(questions:q);chooser=false;learn=true})}.sheet(isPresented:$botanOpen){BotanCoachView(start:{botanOpen=false;recommended()})} } }
 private var topBar:some View { HStack{Text("BOTAI").font(.title2.bold()).foregroundStyle(.cyan);Spacer();Label("4 дня",systemImage:"flame.fill").foregroundStyle(.orange);Button{profile=true}label:{Image(systemName:"gearshape.fill").font(.title2)}}.padding(.top,6) }
 private var motivation:some View { HStack(spacing:14){ZStack{Circle().stroke(.white.opacity(0.08),lineWidth:9);Circle().trim(from:0,to:0.50).stroke(.mint,style:StrokeStyle(lineWidth:9,lineCap:.round)).rotationEffect(.degrees(-90));VStack(spacing:0){Text("50%").font(.title2.bold());Text("сегодня").font(.system(size:9))}}.frame(width:82,height:82);VStack(alignment:.leading,spacing:5){Text("Ты молодец — уже лучше вчера").font(.headline);HStack(spacing:12){compare("40%","ВЧЕРА");compare("46%","7 ДНЕЙ");compare("80%","РЕКОРД")};Text("До личного рекорда ещё 30%").font(.caption).foregroundStyle(.cyan)}}.padding(12).background(.black.opacity(0.3),in:RoundedRectangle(cornerRadius:22)).overlay(RoundedRectangle(cornerRadius:22).stroke(.mint.opacity(0.3))) }
 private func compare(_ value:String,_ label:String)->some View{VStack(alignment:.leading,spacing:0){Text(value).font(.subheadline.bold());Text(label).font(.system(size:8)).foregroundStyle(.white.opacity(0.55))}}
 private var goalStrip:some View { HStack(spacing:8){GoalRing(icon:"questionmark",value:0.64,text:"32/50",caption:"ВОПРОСЫ",tint:.mint);GoalRing(icon:"timer",value:0.6,text:"24/40",caption:"МИНУТЫ",tint:.cyan);GoalRing(icon:"book.fill",value:0.63,text:"44/70",caption:"ЗНАНИЯ",tint:.purple);GoalRing(icon:"flame.fill",value:0.4,text:"4/10",caption:"ДНИ",tint:.orange)}.padding(.vertical,4) }
 private var forecast:some View { HStack(spacing:12){Image(systemName:"waveform.path.ecg").font(.title2).foregroundStyle(.orange);VStack(alignment:.leading,spacing:3){Text("РИСК НЕ УСПЕТЬ К ЦЕЛИ").font(.caption.bold()).foregroundStyle(.orange);Text("Осталось 5 дней · при этом темпе нужно 10").font(.subheadline.bold());Text("+20 минут в день → успеешь").font(.caption).foregroundStyle(.white.opacity(0.7))};Spacer()}.padding(11).background(.orange.opacity(0.09),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(.orange.opacity(0.35))) }
 private var recommendation:some View { HStack(spacing:12){Image(systemName:"sparkles").font(.title2).foregroundStyle(.cyan);VStack(alignment:.leading,spacing:2){Text("Ботан советует").font(.caption.bold()).foregroundStyle(.cyan);Text("12 слабых вопросов · ≈5 мин").font(.headline)};Spacer();Button("Старт"){recommended()}.buttonStyle(.borderedProminent)}.padding(11).background(.blue.opacity(0.1),in:RoundedRectangle(cornerRadius:18)) }
 private var actions:some View { HStack(spacing:10){Button{recommended()}label:{Label("ИГРАТЬ",systemImage:"play.fill").frame(maxWidth:.infinity)}.buttonStyle(.borderedProminent).controlSize(.large);Button{chooser=true}label:{Label("Выбрать",systemImage:"slider.horizontal.3").frame(maxWidth:.infinity)}.buttonStyle(.bordered).controlSize(.large)}.padding(.trailing,94) }
 private func recommended(){store.use(questions:MVPDemoData.questions(for:plans[0]));learn=true}
}

private struct DigitalBackground:View{var body:some View{ZStack{LinearGradient(colors:[Color(red:0.015,green:0.035,blue:0.12),Color(red:0.03,green:0.08,blue:0.18),.black],startPoint:.top,endPoint:.bottom).ignoresSafeArea();Canvas{c,s in for x in stride(from:0.0,through:s.width,by:32){var p=Path();p.move(to:.init(x:x,y:0));p.addLine(to:.init(x:x,y:s.height));c.stroke(p,with:.color(.cyan.opacity(0.035)))};for y in stride(from:0.0,through:s.height,by:32){var p=Path();p.move(to:.init(x:0,y:y));p.addLine(to:.init(x:s.width,y:y));c.stroke(p,with:.color(.cyan.opacity(0.035)))}}.ignoresSafeArea()}}}
private struct BotanRobot:View{var body:some View{ZStack{Ellipse().fill(.cyan.opacity(0.18)).frame(width:110,height:28).offset(y:54);RoundedRectangle(cornerRadius:30).fill(.white).frame(width:92,height:78).offset(y:20);RoundedRectangle(cornerRadius:26).fill(.white).frame(width:100,height:76).offset(y:-30);RoundedRectangle(cornerRadius:22).fill(Color(red:0.01,green:0.05,blue:0.1)).frame(width:82,height:57).offset(y:-30);HStack(spacing:28){Circle().fill(.cyan);Circle().fill(.cyan)}.frame(width:64).offset(y:-35);Capsule().fill(.cyan).frame(width:28,height:5).offset(y:-17);Image(systemName:"leaf.fill").foregroundStyle(.green).font(.title2).offset(x:12,y:-76);Circle().fill(.cyan).frame(width:17,height:17).offset(y:15)}}}
private struct HexBadge:View{let text:String;let caption:String;var body:some View{VStack(spacing:0){Text(text).font(.title2.bold());Text(caption).font(.caption2)}.foregroundStyle(.cyan).frame(width:54,height:50).background(.black.opacity(0.3),in:RoundedRectangle(cornerRadius:14)).overlay(RoundedRectangle(cornerRadius:14).stroke(.cyan))}}
private struct HUDChip:View{let icon:String;let value:String;let caption:String;let tint:Color;var body:some View{HStack(spacing:5){Image(systemName:icon).foregroundStyle(tint);VStack(alignment:.leading,spacing:0){Text(caption).font(.system(size:8)).foregroundStyle(.white.opacity(0.6));Text(value).font(.headline.bold())}}.padding(.horizontal,8).frame(height:50).background(.black.opacity(0.3),in:RoundedRectangle(cornerRadius:14)).overlay(RoundedRectangle(cornerRadius:14).stroke(tint.opacity(0.5)))}}
private struct MiniBars:View{var body:some View{HStack(alignment:.bottom,spacing:4){ForEach([0.35,0.55,0.42,0.8,1.0],id:\.self){v in Capsule().fill(.cyan).frame(width:7,height:36*v)}}}}
private struct Orb:View{let icon:String;let tint:Color;var body:some View{Image(systemName:icon).foregroundStyle(.white).frame(width:44,height:44).background(tint,in:Circle()).shadow(color:tint,radius:10)}}
private struct GoalRing:View{let icon:String;let value:Double;let text:String;let caption:String;let tint:Color;var body:some View{VStack(spacing:4){ZStack{Circle().stroke(.white.opacity(0.1),lineWidth:7);Circle().trim(from:0,to:value).stroke(tint,style:StrokeStyle(lineWidth:7,lineCap:.round)).rotationEffect(.degrees(-90));Image(systemName:icon).foregroundStyle(tint)}.frame(width:60,height:60).shadow(color:tint.opacity(0.35),radius:7);Text(text).font(.caption.bold());Text(caption).font(.system(size:8)).foregroundStyle(.white.opacity(0.6))}.frame(maxWidth:.infinity)}}
private struct MixChooserView:View { let start:([StudyQuestion])->Void; @Environment(\.dismiss) private var dismiss; @State private var selected:Set<UUID>=Set(MVPDemoData.plans.map(\.id)); var body:some View{NavigationStack{VStack(spacing:16){List(MVPDemoData.plans){p in Button{if selected.contains(p.id){selected.remove(p.id)}else{selected.insert(p.id)}}label:{HStack{Image(systemName:selected.contains(p.id) ? "checkmark.circle.fill":"circle");VStack(alignment:.leading){Text(p.title);Text(p.subtitle).font(.caption).foregroundStyle(.secondary)}}}};Button("НАЧАТЬ МИКС"){let qs=MVPDemoData.plans.filter{selected.contains($0.id)}.flatMap{MVPDemoData.questions(for:$0)}.shuffled();start(Array(qs.prefix(20)))}.buttonStyle(.borderedProminent).disabled(selected.isEmpty).padding()}.navigationTitle("Выбрать разделы").toolbar{ToolbarItem(placement:.cancellationAction){Button("Закрыть"){dismiss()}}}}} }
private struct ComparisonChart:View { let today:Double; let yesterday:Double; let record:Double
 var body:some View { GeometryReader { g in ZStack(alignment:.leading){ Capsule().fill(.white.opacity(0.08)).frame(height:10); Capsule().fill(.mint).frame(width:g.size.width*today,height:10); marker(g.size.width*yesterday,"В"); marker(g.size.width*record,"R") } }.frame(height:22) }
 private func marker(_ x:Double,_ text:String)->some View { Text(text).font(.system(size:8,weight:.bold)).foregroundStyle(.white).frame(width:18,height:18).background(.black,in:Circle()).overlay(Circle().stroke(.white.opacity(0.6))).offset(x:max(0,x-9),y:-4) }
}
private struct ForecastMetric:View { let value:String; let label:String; var body:some View { VStack(spacing:3){Text(value).font(.headline.bold()).foregroundStyle(.cyan);Text(label).font(.system(size:9)).foregroundStyle(.white.opacity(0.62)).multilineTextAlignment(.center)}.frame(maxWidth:.infinity).padding(.vertical,8).background(.black.opacity(0.2),in:RoundedRectangle(cornerRadius:12)) } }
private struct BotanCoachView:View { let start:()->Void; @Environment(\.dismiss) private var dismiss; var body:some View{NavigationStack{VStack(spacing:18){BotanRobot().frame(width:170,height:190);Text("Что делать сейчас?").font(.title.bold());Text("Ты идёшь лучше вчера, но по цели химии немного отстаёшь. Я бы сейчас повторил 12 слабых вопросов — это около 5 минут.").multilineTextAlignment(.center).foregroundStyle(.secondary);Button("Сделать как советует Ботан"){start()}.buttonStyle(.borderedProminent).controlSize(.large);Button("Не сейчас"){dismiss()}.buttonStyle(.bordered);Spacer()}.padding().navigationTitle("Ботан").navigationBarTitleDisplayMode(.inline)}} }
