import SwiftUI
struct GameHomeView: View {
 @Environment(LearningStore.self) private var store; @State private var learn=false; @State private var profile=false; @State private var chooser=false
 private let plans=MVPDemoData.plans
 var body:some View { NavigationStack { ZStack { DigitalBackground(); ScrollView(showsIndicators:false){VStack(spacing:14){topBar; motivation; forecast; primaryGoal; recommendation; secondaryGoals}.padding(.horizontal,14).padding(.bottom,26)} }.toolbar(.hidden,for:.navigationBar).sheet(isPresented:$learn){LearnSessionView()}.sheet(isPresented:$profile){NavigationStack{ProfileView()}}.sheet(isPresented:$chooser){MixChooserView(start:{q in store.use(questions:q);chooser=false;learn=true})} } }
 private var topBar:some View { HStack{Text("BOTAI").font(.title2.bold()).foregroundStyle(.cyan);Spacer();Label("4 дня",systemImage:"flame.fill").foregroundStyle(.orange);Button{profile=true}label:{Image(systemName:"gearshape.fill").font(.title2)}}.padding(.top,8) }
 private var motivation:some View { ZStack{
  RoundedRectangle(cornerRadius:26).fill(LinearGradient(colors:[.mint.opacity(0.20),.cyan.opacity(0.08),.black.opacity(0.34)],startPoint:.topLeading,endPoint:.bottomTrailing))
  VStack(spacing:8){HStack(alignment:.center,spacing:12){ZStack{Circle().stroke(.white.opacity(0.08),lineWidth:11);Circle().trim(from:0,to:0.50).stroke(AngularGradient(colors:[.mint,.cyan],center:.center),style:StrokeStyle(lineWidth:11,lineCap:.round)).rotationEffect(.degrees(-90));VStack(spacing:0){Text("50%").font(.system(size:34,weight:.bold,design:.rounded)).foregroundStyle(.white);Text("ОСВОЕНО").font(.system(size:8,weight:.bold)).foregroundStyle(.white.opacity(0.78))}}.frame(width:102,height:102);
    VStack(spacing:5){Text("КИСЛОТЫ И КИСЛОТНЫЕ ОСТАТКИ").font(.system(size:10,weight:.bold)).foregroundStyle(.cyan).lineLimit(1).minimumScaleFactor(0.8);HStack(spacing:6){MiniCompare(value:"40",label:"ВЧЕРА");MiniCompare(value:"46",label:"СРЕДНЕЕ");MiniCompare(value:"80",label:"РЕКОРД")}}.frame(maxWidth:.infinity)}
   Button{recommended()}label:{HStack{Text("ПРОДОЛЖИТЬ И ПОДНЯТЬ РЕЗУЛЬТАТ").font(.caption.bold());Spacer();Image(systemName:"play.fill")}.foregroundStyle(.white).padding(.horizontal,14).frame(height:38).background(Color.blue.opacity(0.88),in:Capsule()).overlay(Capsule().stroke(.cyan.opacity(0.7),lineWidth:1))}.buttonStyle(.plain)
  }.padding(.horizontal,14).padding(.vertical,11)
 }.overlay(RoundedRectangle(cornerRadius:26).stroke(.mint.opacity(0.38))) }
 private var forecast:some View { VStack(alignment:.leading,spacing:9){HStack{Label("ПРОГНОЗ",systemImage:"waveform.path.ecg").font(.caption.bold()).foregroundStyle(.cyan);Spacer();Text("5 дней осталось").font(.caption).foregroundStyle(.orange)};Text("По химии ты знаешь 40% материала").font(.headline);HStack(spacing:8){ForecastMetric(value:"20 мин",label:"среднее занятие");ForecastMetric(value:"+18%",label:"за 10 дней");ForecastMetric(value:"10 дней",label:"нужно при этом темпе")};Text("До цели осталось 5 дней. При текущем темпе понадобится около 10. Поднажми: +20 минут в день — и успеешь.").font(.subheadline).foregroundStyle(.white.opacity(0.82));HStack{Image(systemName:"exclamationmark.triangle.fill").foregroundStyle(.orange);Text("Сегодня лучше добавить ещё одно короткое занятие").font(.caption.bold())}}.padding(14).background(.orange.opacity(0.09),in:RoundedRectangle(cornerRadius:22)).overlay(RoundedRectangle(cornerRadius:22).stroke(.orange.opacity(0.38))) }
 private var primaryGoal:some View { VStack(alignment:.leading,spacing:10){HStack{Text("ТЕКУЩАЯ ЦЕЛЬ").font(.caption.bold()).foregroundStyle(.cyan);Spacer();Text("18 осталось").font(.caption).foregroundStyle(.mint)};HStack(spacing:16){GoalRing(icon:"questionmark",value:0.64,text:"32/50",caption:"ВОПРОСОВ",tint:.mint);VStack(alignment:.leading,spacing:5){Text("Пройти 50 вопросов сегодня").font(.headline);Text("32 выполнено · 18 осталось").font(.subheadline).foregroundStyle(.white.opacity(0.72));Text("Вчера: 24  •  рекорд: 61").font(.caption).foregroundStyle(.white.opacity(0.55))};Spacer()}}.padding(14).background(.black.opacity(0.24),in:RoundedRectangle(cornerRadius:22)) }
 private var recommendation:some View { VStack(alignment:.leading,spacing:10){Label("БОТАН РЕКОМЕНДУЕТ",systemImage:"sparkles").font(.caption.bold()).foregroundStyle(.cyan);Text("Повторить 12 слабых вопросов").font(.title3.bold());Text("12 вопросов · ≈ 5 минут · ошибки последних занятий · закроет часть дневной цели").font(.caption).foregroundStyle(.white.opacity(0.7));Button{recommended()}label:{Label("НАЧАТЬ РЕКОМЕНДАЦИЮ",systemImage:"play.fill").frame(maxWidth:.infinity).padding(.vertical,6)}.buttonStyle(.borderedProminent);Button{chooser=true}label:{Text("Выбрать другую тренировку").frame(maxWidth:.infinity)}}.padding(14).background(.blue.opacity(0.12),in:RoundedRectangle(cornerRadius:22)).overlay(RoundedRectangle(cornerRadius:22).stroke(.blue.opacity(0.45))) }
 private var secondaryGoals:some View { HStack(spacing:8){GoalRing(icon:"timer",value:0.6,text:"24/40",caption:"МИНУТЫ",tint:.cyan);GoalRing(icon:"book.fill",value:0.63,text:"44/70",caption:"ОСВОЕНО",tint:.purple);GoalRing(icon:"flame.fill",value:0.4,text:"4/10",caption:"ДНИ",tint:.orange)} }
 private func recommended(){store.use(questions:MVPDemoData.questions(for:plans[0]));learn=true}; private func random(){store.use(questions:Array(plans.flatMap{MVPDemoData.questions(for:$0)}.shuffled().prefix(15)));learn=true}
}
private struct DigitalBackground:View{var body:some View{ZStack{LinearGradient(colors:[Color(red:0.015,green:0.035,blue:0.12),Color(red:0.03,green:0.08,blue:0.18),.black],startPoint:.top,endPoint:.bottom).ignoresSafeArea();Canvas{c,s in for x in stride(from:0.0,through:s.width,by:32){var p=Path();p.move(to:.init(x:x,y:0));p.addLine(to:.init(x:x,y:s.height));c.stroke(p,with:.color(.cyan.opacity(0.035)))};for y in stride(from:0.0,through:s.height,by:32){var p=Path();p.move(to:.init(x:0,y:y));p.addLine(to:.init(x:s.width,y:y));c.stroke(p,with:.color(.cyan.opacity(0.035)))}}.ignoresSafeArea()}}}
private struct BotanRobot:View{var body:some View{ZStack{Ellipse().fill(.cyan.opacity(0.18)).frame(width:110,height:28).offset(y:54);RoundedRectangle(cornerRadius:30).fill(.white).frame(width:92,height:78).offset(y:20);RoundedRectangle(cornerRadius:26).fill(.white).frame(width:100,height:76).offset(y:-30);RoundedRectangle(cornerRadius:22).fill(Color(red:0.01,green:0.05,blue:0.1)).frame(width:82,height:57).offset(y:-30);HStack(spacing:28){Circle().fill(.cyan);Circle().fill(.cyan)}.frame(width:64).offset(y:-35);Capsule().fill(.cyan).frame(width:28,height:5).offset(y:-17);Image(systemName:"leaf.fill").foregroundStyle(.green).font(.title2).offset(x:12,y:-76);Circle().fill(.cyan).frame(width:17,height:17).offset(y:15)}}}
private struct HexBadge:View{let text:String;let caption:String;var body:some View{VStack(spacing:0){Text(text).font(.title2.bold());Text(caption).font(.caption2)}.foregroundStyle(.cyan).frame(width:54,height:50).background(.black.opacity(0.3),in:RoundedRectangle(cornerRadius:14)).overlay(RoundedRectangle(cornerRadius:14).stroke(.cyan))}}
private struct HUDChip:View{let icon:String;let value:String;let caption:String;let tint:Color;var body:some View{HStack(spacing:5){Image(systemName:icon).foregroundStyle(tint);VStack(alignment:.leading,spacing:0){Text(caption).font(.system(size:8)).foregroundStyle(.white.opacity(0.6));Text(value).font(.headline.bold())}}.padding(.horizontal,8).frame(height:50).background(.black.opacity(0.3),in:RoundedRectangle(cornerRadius:14)).overlay(RoundedRectangle(cornerRadius:14).stroke(tint.opacity(0.5)))}}
private struct MiniBars:View{var body:some View{HStack(alignment:.bottom,spacing:4){ForEach([0.35,0.55,0.42,0.8,1.0],id:\.self){v in Capsule().fill(.cyan).frame(width:7,height:36*v)}}}}
private struct Orb:View{let icon:String;let tint:Color;var body:some View{Image(systemName:icon).foregroundStyle(.white).frame(width:44,height:44).background(tint,in:Circle()).shadow(color:tint,radius:10)}}
private struct GoalRing:View{let icon:String;let value:Double;let text:String;let caption:String;let tint:Color;var body:some View{VStack(spacing:4){ZStack{Circle().stroke(.white.opacity(0.1),lineWidth:7);Circle().trim(from:0,to:value).stroke(tint,style:StrokeStyle(lineWidth:7,lineCap:.round)).rotationEffect(.degrees(-90));Image(systemName:icon).foregroundStyle(tint)}.frame(width:60,height:60).shadow(color:tint.opacity(0.35),radius:7);Text(text).font(.caption.bold());Text(caption).font(.system(size:8)).foregroundStyle(.white.opacity(0.6))}.frame(maxWidth:.infinity)}}
private struct MixChooserView:View { let start:([StudyQuestion])->Void; @Environment(\.dismiss) private var dismiss; @State private var selected:Set<UUID>=Set(MVPDemoData.plans.map(\.id)); var body:some View{NavigationStack{VStack(spacing:16){List(MVPDemoData.plans){p in Button{if selected.contains(p.id){selected.remove(p.id)}else{selected.insert(p.id)}}label:{HStack{Image(systemName:selected.contains(p.id) ? "checkmark.circle.fill":"circle");VStack(alignment:.leading){Text(p.title);Text(p.subtitle).font(.caption).foregroundStyle(.secondary)}}}};Button("НАЧАТЬ МИКС"){let qs=MVPDemoData.plans.filter{selected.contains($0.id)}.flatMap{MVPDemoData.questions(for:$0)}.shuffled();start(Array(qs.prefix(20)))}.buttonStyle(.borderedProminent).disabled(selected.isEmpty).padding()}.navigationTitle("Выбрать разделы").toolbar{ToolbarItem(placement:.cancellationAction){Button("Закрыть"){dismiss()}}}}} }
private struct ComparisonChart:View { let today:Double; let yesterday:Double; let record:Double
 var body:some View { GeometryReader { g in ZStack(alignment:.leading){ Capsule().fill(.white.opacity(0.08)).frame(height:10); Capsule().fill(.mint).frame(width:g.size.width*today,height:10); marker(g.size.width*yesterday,"В"); marker(g.size.width*record,"R") } }.frame(height:22) }
 private func marker(_ x:Double,_ text:String)->some View { Text(text).font(.system(size:8,weight:.bold)).foregroundStyle(.white).frame(width:18,height:18).background(.black,in:Circle()).overlay(Circle().stroke(.white.opacity(0.6))).offset(x:max(0,x-9),y:-4) }
}
private struct ForecastMetric:View { let value:String; let label:String; var body:some View { VStack(spacing:3){Text(value).font(.headline.bold()).foregroundStyle(.cyan);Text(label).font(.system(size:9)).foregroundStyle(.white.opacity(0.62)).multilineTextAlignment(.center)}.frame(maxWidth:.infinity).padding(.vertical,8).background(.black.opacity(0.2),in:RoundedRectangle(cornerRadius:12)) } }
private struct MiniCompare:View { let value:String; let label:String; var body:some View { VStack(spacing:3){Text(value+"%").font(.system(size:21,weight:.bold,design:.rounded)).foregroundStyle(.white);Text(label).font(.system(size:9,weight:.bold)).foregroundStyle(.cyan.opacity(0.9))}.frame(maxWidth:.infinity,minHeight:62).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:12)).overlay(RoundedRectangle(cornerRadius:12).stroke(.white.opacity(0.08))) } }
