import SwiftUI
struct TodayView: View {
 @Environment(LearningStore.self) private var store
 @State private var showingLearn=false; @State private var showingPlans=false
 private let plans=MVPDemoData.plans
 var body:some View { NavigationStack { ScrollView { VStack(spacing:18){ hero; if let p=plans.first { mission(p) }; streak; Text("Ещё миссии").font(.title3.bold()).frame(maxWidth:.infinity,alignment:.leading); ForEach(plans.dropFirst()){p in Button{start(p)}label:{missionRow(p)}.buttonStyle(.plain)}; Button("Карта всех миссий"){showingPlans=true}.buttonStyle(.bordered) }.padding() }.navigationTitle("BOTAI").sheet(isPresented:$showingLearn){LearnSessionView()}.sheet(isPresented:$showingPlans){NavigationStack{PlansView()}} } }
 private var hero:some View { HStack(spacing:14){ ZStack{Circle().fill(.blue.opacity(0.15)).frame(width:68,height:68);Image(systemName:"brain.head.profile").font(.system(size:34)).foregroundStyle(.blue)}; VStack(alignment:.leading,spacing:5){Text("Уровень \(GameDemo.level)").font(.title2.bold());ProgressView(value:Double(GameDemo.xp),total:Double(GameDemo.nextLevelXP));Text("\(GameDemo.xp) / \(GameDemo.nextLevelXP) XP").font(.caption).foregroundStyle(.secondary)};Spacer();Label("\(GameDemo.coins)",systemImage:"star.circle.fill").font(.headline)} }
 private func mission(_ p:MVPDemoData.Plan)->some View { GroupBox { VStack(alignment:.leading,spacing:12){Label("МИССИЯ ДНЯ",systemImage:"flag.checkered").font(.caption.bold()).foregroundStyle(.orange);Text("Лаборатория кислот").font(.title2.bold());Text("Пройди испытание и приблизься к следующему уровню").foregroundStyle(.secondary);HStack{badge("arrow.clockwise","\(p.due) повторить");badge("sparkles","\(p.fresh) новых");badge("clock","~\(p.minutes) мин")};Button("НАЧАТЬ МИССИЮ  +120 XP"){start(p)}.buttonStyle(.borderedProminent).controlSize(.large).frame(maxWidth:.infinity);ProgressView(value:p.progress);Text("Лаборатория открыта на \(Int(p.progress*100))%").font(.caption).foregroundStyle(.secondary)}} }
 private var streak:some View { HStack{Image(systemName:"flame.fill").font(.title).foregroundStyle(.orange);VStack(alignment:.leading){Text("Серия: \(GameDemo.streak) дня").font(.headline);Text("Ещё одно занятие завтра — и будет 5!").font(.caption).foregroundStyle(.secondary)};Spacer()} .padding().background(.orange.opacity(0.08),in:RoundedRectangle(cornerRadius:16)) }
 private func missionRow(_ p:MVPDemoData.Plan)->some View { HStack(spacing:12){Image(systemName:p.id==MVPDemoData.englishID ? "text.bubble.fill":"globe.europe.africa.fill").font(.title2).frame(width:42,height:42).background(.blue.opacity(0.1),in:Circle());VStack(alignment:.leading){Text(p.title).font(.headline);Text("\(p.today) заданий · +\(p.today*6) XP").font(.caption).foregroundStyle(.secondary)};Spacer();Image(systemName:"play.circle.fill").font(.title2)}.padding().background(.thinMaterial,in:RoundedRectangle(cornerRadius:16)) }
 private func badge(_ icon:String,_ text:String)->some View{Label(text,systemImage:icon).font(.caption).padding(7).background(.secondary.opacity(0.08),in:Capsule())}; private func start(_ p:MVPDemoData.Plan){store.use(questions:MVPDemoData.questions(for:p));showingLearn=true}
}
