import SwiftUI
struct TodayView: View {
 @Environment(LearningStore.self) private var store; @State private var showingLearn=false; @State private var showingPlans=false
 private let plans=MVPDemoData.plans
 var body:some View { NavigationStack { ScrollView { VStack(alignment:.leading,spacing:18){ Text("Твой план").font(.title2.bold()); if let p=plans.first { primary(p) }; Text("Сегодня ещё").font(.headline); ForEach(plans.dropFirst()){ p in Button { start(p) } label:{ planRow(p) }.buttonStyle(.plain) }; Button("Все мои планы"){showingPlans=true}; GroupBox("За сегодня"){HStack{metric("\(store.completedToday)","ответов");Spacer();metric("\(store.streak)","дней подряд");Spacer();metric("\(Int(plans.first!.progress*100))%","главная цель")}.frame(maxWidth:.infinity)} }.padding() }.navigationTitle("Сегодня").sheet(isPresented:$showingLearn){LearnSessionView()}.sheet(isPresented:$showingPlans){NavigationStack{PlansView()}} } }
 private func primary(_ p:MVPDemoData.Plan)->some View { GroupBox { VStack(alignment:.leading,spacing:12){Text(p.title).font(.title3.bold());Text(p.subtitle).foregroundStyle(.secondary);ProgressView(value:p.progress);HStack{Text("\(Int(p.progress*100))% освоено");Spacer();Text("~\(p.minutes) мин").foregroundStyle(.secondary)}.font(.subheadline);Button("ПРОДОЛЖИТЬ · \(p.today) ВОПРОСОВ"){start(p)}.buttonStyle(.borderedProminent).controlSize(.large).frame(maxWidth:.infinity);Text("\(p.due) повторить · \(p.fresh) новых").font(.caption).foregroundStyle(.secondary)}} }
 private func planRow(_ p:MVPDemoData.Plan)->some View { GroupBox { VStack(alignment:.leading,spacing:8){HStack{VStack(alignment:.leading){Text(p.title).font(.headline);Text(p.subtitle).font(.caption).foregroundStyle(.secondary)};Spacer();Image(systemName:"play.circle.fill")};ProgressView(value:p.progress);HStack{Text("\(p.today) сегодня · \(Int(p.progress*100))%");Spacer();Text("~\(p.minutes) мин")}.font(.caption).foregroundStyle(.secondary)}} }
 private func start(_ p:MVPDemoData.Plan){store.use(questions:MVPDemoData.questions(for:p));showingLearn=true}; private func metric(_ v:String,_ l:String)->some View{VStack{Text(v).font(.title2.bold());Text(l).font(.caption).foregroundStyle(.secondary)}}
}
