import SwiftUI

struct StudentProgressView: View {
 @Environment(LearningStore.self) private var learning
 private let cal=Calendar.current
 var body:some View{ZStack{ProfileBG();ScrollView{VStack(spacing:14){summary;activity;mastery;history}.padding(16).padding(.bottom,24)}}.navigationTitle("Мой прогресс").navigationBarTitleDisplayMode(.inline)}
 private var summary:some View{VStack(alignment:.leading,spacing:12){Text("МОЙ ПРОГРЕСС").font(.caption.bold()).foregroundStyle(.cyan);HStack(spacing:8){PMetric(value:time(learning.analytics.totalSeconds),label:"ВСЕГО");PMetric(value:"\(learning.masteryPercent)%",label:"ОСВОЕНО");PMetric(value:"\(learning.streak)",label:"СЕРИЯ, ДН.")};if learning.sessions.isEmpty{Text("Статистика заполнится после первой реальной учебной сессии.").font(.caption).foregroundStyle(.white.opacity(0.55))}}.padding(16).profileCard()}
 private var activity:some View{VStack(alignment:.leading,spacing:10){Text("АКТИВНОСТЬ · 7 ДНЕЙ").font(.caption.bold()).foregroundStyle(.cyan);HStack(alignment:.bottom,spacing:7){ForEach(days,id:\.self){d in let sec=learning.analytics.seconds(on:d);VStack(spacing:5){Text(sec == 0 ? "" : "\(max(1,sec/60))").font(.system(size:8,weight:.bold)).foregroundStyle(.cyan);RoundedRectangle(cornerRadius:4).fill(sec > 0 ? Color.cyan.opacity(0.8):Color.white.opacity(0.07)).frame(height:max(5,CGFloat(sec)/CGFloat(maxSeconds)*70));Text(String(d.formatted(.dateTime.weekday(.abbreviated)).prefix(2)).uppercased()).font(.system(size:8,weight:.bold)).foregroundStyle(.white.opacity(0.5))}.frame(maxWidth:.infinity)}}.frame(height:100,alignment:.bottom)}.padding(16).profileCard()}
 private var mastery:some View{VStack(alignment:.leading,spacing:10){Text("ОСВОЕНИЕ").font(.caption.bold()).foregroundStyle(.mint);row("Знаю",count(.known),.mint);row("Закрепляю",count(.reinforcing),.cyan);row("Изучаю",count(.learning),.orange)}.padding(16).profileCard()}
 private var history:some View{VStack(alignment:.leading,spacing:9){Text("ПОСЛЕДНИЕ ЗАНЯТИЯ").font(.caption.bold()).foregroundStyle(.cyan);if learning.sessions.isEmpty{Text("Занятий пока нет").foregroundStyle(.white.opacity(0.5)).padding(.vertical,8)}else{ForEach(learning.sessions.sorted{$0.startedAt>$1.startedAt}.prefix(10)){s in HStack{VStack(alignment:.leading){Text(s.startedAt.formatted(date:.abbreviated,time:.omitted)).font(.subheadline.bold());Text("\(s.answered) ответов · \(s.correct) верно").font(.caption).foregroundStyle(.white.opacity(0.55))};Spacer();Text(time(s.activeSeconds)).font(.subheadline.bold()).foregroundStyle(.cyan)}.foregroundStyle(.white).padding(.vertical,4)}}}.padding(16).profileCard()}
 private func count(_ level:MasteryLevel)->Int{learning.states.values.filter{$0.masteryLevel == level}.count}
 private func row(_ title:String,_ value:Int,_ tint:Color)->some View{HStack{Circle().fill(tint).frame(width:8,height:8);Text(title).foregroundStyle(.white);Spacer();Text("\(value)").font(.headline).foregroundStyle(tint)}}
 private var days:[Date]{let today=cal.startOfDay(for:.now);return (-6...0).compactMap{cal.date(byAdding:.day,value:$0,to:today)}}
 private var maxSeconds:Int{max(60,days.map{learning.analytics.seconds(on:$0)}.max() ?? 60)}
 private func time(_ seconds:Int)->String{if seconds<60{return "\(seconds) сек"};let m=seconds/60;if m<60{return "\(m) мин"};return "\(m/60) ч \(m%60) мин"}
}
private struct PMetric:View{let value:String;let label:String;var body:some View{VStack(spacing:4){Text(value).font(.headline.bold()).foregroundStyle(.white);Text(label).font(.system(size:8,weight:.bold)).foregroundStyle(.cyan)}.frame(maxWidth:.infinity,minHeight:58).background(.black.opacity(0.2),in:RoundedRectangle(cornerRadius:12))}}
