import SwiftUI
struct LearnSessionView: View {
 @Environment(LearningStore.self) private var store; @Environment(\.dismiss) private var dismiss; @Environment(\.scenePhase) private var scenePhase
 @State private var index=0; @State private var revealed=false; @State private var advancing=false; @State private var checked=false; @State private var selection:Set<Int>=[]; @State private var finished=false; @State private var combo=3; @State private var earnedXP=30; @State private var answeredToday=14; @State private var studySecondsToday=27*60; @State private var questionStartedAt=Date(); @State private var activeStartedAt:Date?=Date(); @State private var activeQuestionSeconds:TimeInterval=0; @State private var paused=false; @State private var correctToday=11; @State private var wrongToday=3
 var body:some View{ZStack{LearnDigitalBackground();NavigationStack{if finished{resultView}else{questionView}}.background(.clear)}.preferredColorScheme(.dark).onChange(of:scenePhase){_,phase in handleScenePhase(phase)}}
 private var question:StudyQuestion{store.questions[index]}
 private var questionView:some View{VStack(spacing:0){sessionHeader;ScrollView(showsIndicators:false){VStack(spacing:18){topicBadge;questionCard;answerArea}.padding(.horizontal,18).padding(.top,20).contentShape(Rectangle()).onTapGesture{if (question.kind == .singleChoice || question.kind == .multipleChoice) && checked{animateAdvanceAfterChoice()}}};Button{paused=true;dismiss()}label:{HStack{Image(systemName:"pause.fill");Text("ПРИОСТАНОВИТЬ ЗАНЯТИЕ").font(.headline)}.foregroundStyle(.white.opacity(0.9)).frame(maxWidth:.infinity).frame(height:54).background(.white.opacity(0.055),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(.white.opacity(0.15)))}.buttonStyle(.plain).padding(.horizontal,18).padding(.bottom,8)}.toolbar(.hidden,for:.navigationBar)}
 private var sessionHeader:some View{HStack(spacing:18){GoalRing(value:answeredToday,target:20,label:"ВОПРОСЫ",tint:.mint);GoalRing(value:studySecondsToday/60,target:40,label:"МИНУТЫ",tint:.cyan);AnswerSplitRing(correct:correctToday,wrong:wrongToday);Spacer();Button{}label:{Image(systemName:"slider.horizontal.3").font(.headline).foregroundStyle(.cyan).frame(width:38,height:38).background(.cyan.opacity(0.09),in:Circle())}}.padding(.horizontal,16).padding(.top,10).padding(.bottom,8)}
 private var topicBadge:some View{HStack(spacing:7){Image(systemName:"atom");Text("ХИМИЯ · КИСЛОТЫ").font(.caption.bold())}.foregroundStyle(.cyan).padding(.horizontal,12).padding(.vertical,7).background(.cyan.opacity(0.09),in:Capsule()).overlay(Capsule().stroke(.cyan.opacity(0.25)))}
 private var questionCard:some View{VStack(spacing:14){ZStack{Circle().fill(.cyan.opacity(0.08)).frame(width:66,height:66);Image(systemName:revealed ? "checkmark.seal.fill":"flask.fill").font(.title).foregroundStyle(revealed ? .mint:.cyan).shadow(color:.cyan.opacity(0.7),radius:9)};Text(revealed ? question.answer:question.prompt).font(.system(size:27,weight:.bold,design:.rounded)).foregroundStyle(.white).multilineTextAlignment(.center).minimumScaleFactor(0.75);Text(revealed ? "Нажми оценку ниже":"Нажми на карточку, чтобы перевернуть").font(.caption).foregroundStyle(.white.opacity(0.48))}.padding(.horizontal,18).padding(.vertical,22).frame(maxWidth:.infinity).frame(height:245).background(.black.opacity(0.20),in:RoundedRectangle(cornerRadius:28)).overlay(RoundedRectangle(cornerRadius:28).stroke(LinearGradient(colors:[.cyan.opacity(0.45),.purple.opacity(0.22)],startPoint:.topLeading,endPoint:.bottomTrailing),lineWidth:1)).rotation3DEffect(.degrees(advancing ? 180 : (revealed ? 360:0)),axis:(x:0,y:1,z:0)).animation(.spring(response:0.5,dampingFraction:0.78),value:revealed).onTapGesture{if question.kind == .reveal{revealed.toggle()}else if (question.kind == .singleChoice || question.kind == .multipleChoice) && checked{animateAdvanceAfterChoice()}else if question.kind == .multipleChoice && checked{animateAdvanceAfterChoice()}else if checked{revealed.toggle()}}}
 @ViewBuilder private var answerArea:some View{if question.kind == .reveal || question.kind == .pair{revealAnswer}else{choiceAnswer}}
 private var revealAnswer:some View{Group{if revealed{VStack(spacing:8){confidenceButton("ОТВЕТИЛ ЛЕГКО",.good,.mint);confidenceButton("СОМНЕВАЛСЯ",.hard,.yellow);confidenceButton("ПОВЕЗЛО — УГАДАЛ",.hard,.orange);confidenceButton("НАДО ПОВТОРЯТЬ",.again,.pink)}}else{Color.clear}}.frame(height:220)}
 private func confidenceButton(_ title:String,_ value:RecallRating,_ color:Color)->some View{Button{submit(value)}label:{HStack{Circle().fill(color).frame(width:8,height:8);Text(title).font(.subheadline.bold());Spacer();Image(systemName:"chevron.right")}.foregroundStyle(.white).padding(.horizontal,16).frame(height:46).background(color.opacity(0.10),in:RoundedRectangle(cornerRadius:15)).overlay(RoundedRectangle(cornerRadius:15).stroke(color.opacity(0.35)))}.buttonStyle(.plain)}
 private var choiceAnswer:some View{VStack(spacing:10){ForEach(Array(question.choices.prefix(6).enumerated()),id:\.offset){i,c in Button{if (question.kind == .singleChoice || question.kind == .multipleChoice) && checked{animateAdvanceAfterChoice()}else{choose(i)}}label:{HStack(spacing:12){Text(["A","B","C","D"][min(i,3)]).font(.caption.bold()).frame(width:30,height:30).background(choiceColor(i).opacity(0.18),in:Circle());Text(c).font(.body.weight(.semibold));Spacer();if checked && question.correctChoiceIndexes.contains(i){Image(systemName:"checkmark.circle.fill")}}.foregroundStyle(choiceColor(i)).padding(.horizontal,14).frame(minHeight:58).background(choiceColor(i).opacity(0.07),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(choiceColor(i).opacity(0.38)))}.buttonStyle(.plain).disabled(checked)};if question.kind == .multipleChoice && !checked{Button{checkAnswers()}label:{Text("ОТВЕТИТЬ").font(.headline).foregroundStyle(.white).frame(maxWidth:.infinity).frame(height:54).background(selection.isEmpty ? Color.white.opacity(0.08):Color.blue.opacity(0.8),in:RoundedRectangle(cornerRadius:18))}.disabled(selection.isEmpty)};if checked{Text(question.kind == .singleChoice ? "Правильный ответ подсвечен · нажми ещё раз, чтобы дальше" : "Правильные ответы подсвечены · нажми ещё раз, чтобы дальше").font(.caption).foregroundStyle(.mint);if revealed && question.kind != .singleChoice && question.kind != .multipleChoice{ratingButtons}}}}
 private func choiceColor(_ i:Int)->Color{if checked{return question.correctChoiceIndexes.contains(i) ? .mint : (selection.contains(i) ? .orange:.white)};return selection.contains(i) ? .cyan:.white}
 private func choose(_ i:Int){if question.kind == .singleChoice{selection=[i];checkAnswers()}else if selection.contains(i){selection.remove(i)}else{selection.insert(i)}}
 private func animateAdvanceAfterChoice(){guard !advancing else{return};withAnimation(.easeIn(duration:0.22)){advancing=true};DispatchQueue.main.asyncAfter(deadline:.now()+0.22){advanceAfterChoice();withAnimation(.easeOut(duration:0.22)){advancing=false}}}
 private func advanceAfterChoice(){countQuestionTime();answeredToday+=1;let ok=selection == question.correctChoiceIndexes;if ok{correctToday+=1}else{wrongToday+=1};store.record(question:question,rating:ok ? .good:.again);if index+1<store.questions.count{index+=1;questionStartedAt=Date();activeStartedAt = scenePhase == .active ? Date():nil;activeQuestionSeconds=0;revealed=false;checked=false;selection=[]}else{finished=true}}
 private func checkAnswers(){withAnimation(.easeInOut(duration:0.2)){checked=true}}
 private var ratingButtons:some View{HStack(spacing:8){rating("НЕ ПОМНЮ",.again,.orange);rating("С ТРУДОМ",.hard,.yellow);rating("ЗНАЮ",.good,.mint)}}
 private func rating(_ title:String,_ value:RecallRating,_ color:Color)->some View{Button{submit(value)}label:{Text(title).font(.system(size:11,weight:.bold)).foregroundStyle(color).frame(maxWidth:.infinity).frame(height:44).background(color.opacity(0.10),in:RoundedRectangle(cornerRadius:14)).overlay(RoundedRectangle(cornerRadius:14).stroke(color.opacity(0.35)))}.buttonStyle(.plain)}
 private var resultView:some View{VStack(spacing:20){Spacer();ZStack{Circle().fill(.cyan.opacity(0.12)).frame(width:150,height:150);Image(systemName:"sparkles").font(.system(size:66)).foregroundStyle(.cyan).shadow(color:.cyan,radius:18)};Text("ВОПРОСЫ ЗАКОНЧИЛИСЬ").font(.largeTitle.bold()).foregroundStyle(.white);Text("Сегодня: \(answeredToday) вопросов · \(studySecondsToday/60) мин").font(.title3.bold()).foregroundStyle(.cyan);Button("ГОТОВО"){dismiss()}.buttonStyle(.borderedProminent).controlSize(.large);Spacer()}.padding()}
 private func toggle(_ i:Int){if question.kind == .singleChoice{selection=[i]}else if selection.contains(i){selection.remove(i)}else{selection.insert(i)}}
 private func submit(_ r:RecallRating){countQuestionTime();answeredToday+=1;if r == .good{correctToday+=1}else{wrongToday+=1};store.record(question:question,rating:r);if r == .good{combo+=1;earnedXP+=10}else if r == .hard{earnedXP+=6}else{combo=0;earnedXP+=3};if index+1<store.questions.count{index+=1;questionStartedAt=Date();activeStartedAt = scenePhase == .active ? Date():nil;activeQuestionSeconds=0;revealed=false;checked=false;selection=[]}else{finished=true}}
 private func countQuestionTime(){var total=activeQuestionSeconds;if let start=activeStartedAt{total += Date().timeIntervalSince(start)};studySecondsToday += max(0,Int(total));activeStartedAt=nil;activeQuestionSeconds=0}
 private func handleScenePhase(_ phase:ScenePhase){switch phase{case .active: if activeStartedAt == nil{activeStartedAt=Date()};case .inactive,.background: if let start=activeStartedAt{activeQuestionSeconds += Date().timeIntervalSince(start);activeStartedAt=nil};@unknown default:break}}

}
private struct LearnDigitalBackground:View{var body:some View{ZStack{LinearGradient(colors:[Color(red:0.015,green:0.025,blue:0.08),Color(red:0.025,green:0.055,blue:0.14),Color(red:0.08,green:0.025,blue:0.16)],startPoint:.topLeading,endPoint:.bottomTrailing).ignoresSafeArea();Circle().fill(.cyan.opacity(0.10)).frame(width:280,height:280).blur(radius:70).offset(x:-150,y:-270);Circle().fill(.purple.opacity(0.12)).frame(width:300,height:300).blur(radius:80).offset(x:160,y:250)}}}
private struct GoalRing:View{let value:Int;let target:Int;let label:String;let tint:Color
 var body:some View{let ratio=CGFloat(value)/CGFloat(max(target,1));ZStack{Circle().stroke(.white.opacity(0.08),lineWidth:8);Circle().trim(from:0,to:min(ratio,1)).stroke(tint,style:StrokeStyle(lineWidth:8,lineCap:.round)).rotationEffect(.degrees(-90)).shadow(color:tint.opacity(0.5),radius:5);if ratio>1{Circle().trim(from:0,to:min(ratio-1,1)).stroke(tint.opacity(0.45),style:StrokeStyle(lineWidth:4,lineCap:.round)).rotationEffect(.degrees(-90)).padding(7)};VStack(spacing:0){Text("\(value)").font(.title3.bold().monospacedDigit());Text("/\(target)").font(.caption2.bold()).foregroundStyle(.white.opacity(0.55))}}.frame(width:78,height:78).overlay(alignment:.bottom){Text(label).font(.system(size:9,weight:.bold)).foregroundStyle(.white.opacity(0.72)).offset(y:16)}}}
private struct AnswerSplitRing:View{let correct:Int;let wrong:Int
 var body:some View{let total=max(correct+wrong,1);let good=CGFloat(correct)/CGFloat(total);ZStack{Circle().stroke(.white.opacity(0.08),lineWidth:8);Circle().trim(from:0,to:good).stroke(.green,style:StrokeStyle(lineWidth:8,lineCap:.butt)).rotationEffect(.degrees(-90));Circle().trim(from:good,to:1).stroke(.red,style:StrokeStyle(lineWidth:8,lineCap:.butt)).rotationEffect(.degrees(-90));VStack(spacing:1){HStack(spacing:4){Text("\(correct)").foregroundStyle(.green);Text("/");Text("\(wrong)").foregroundStyle(.red)}.font(.headline.bold().monospacedDigit())}}.frame(width:78,height:78).overlay(alignment:.bottom){Text("ОТВЕТЫ").font(.system(size:9,weight:.bold)).foregroundStyle(.white.opacity(0.72)).offset(y:16)}}}
