import SwiftUI
struct LearnSessionView: View {
 @Environment(LearningStore.self) private var store; @Environment(\.dismiss) private var dismiss; @Environment(\.scenePhase) private var scenePhase
 @State private var index=0; @State private var revealed=false; @State private var advancing=false; @State private var checked=false; @State private var selection:Set<Int>=[]; @State private var finished=false; @State private var combo=3; @State private var earnedXP=30; @State private var answeredToday=14; @State private var studySecondsToday=27*60; @State private var questionStartedAt=Date(); @State private var activeStartedAt:Date?=Date(); @State private var activeQuestionSeconds:TimeInterval=0; @State private var paused=false
 var body:some View{ZStack{LearnDigitalBackground();NavigationStack{if finished{resultView}else{questionView}}.background(.clear)}.preferredColorScheme(.dark).onChange(of:scenePhase){_,phase in handleScenePhase(phase)}}
 private var question:StudyQuestion{store.questions[index]}
 private var questionView:some View{VStack(spacing:0){sessionHeader;ScrollView(showsIndicators:false){VStack(spacing:18){topicBadge;questionCard;answerArea}.padding(.horizontal,18).padding(.top,20).contentShape(Rectangle()).onTapGesture{if (question.kind == .singleChoice || question.kind == .multipleChoice) && checked{animateAdvanceAfterChoice()}}};HStack{Label("Серия \(combo)",systemImage:"bolt.fill").foregroundStyle(.orange);Spacer();Button{ }label:{Label("Режим",systemImage:"slider.horizontal.3").foregroundStyle(.cyan)}}.font(.caption.bold()).padding(.horizontal,22).padding(.vertical,12)}.toolbar(.hidden,for:.navigationBar)}
 private var sessionHeader:some View{VStack(spacing:10){HStack{Button{paused=true;dismiss()}label:{Text("ПАУЗА").font(.caption.bold()).foregroundStyle(.white).padding(.horizontal,12).frame(height:36).background(.white.opacity(0.08),in:Capsule())};Spacer();HStack(spacing:12){DailyHUD(icon:"questionmark.circle.fill",value:"\(answeredToday)/20",done:answeredToday>=20);DailyHUD(icon:"clock.fill",value:"\(studySecondsToday/60)/40 мин",done:studySecondsToday>=40*60)};Spacer();Button{}label:{Image(systemName:"gearshape.fill").foregroundStyle(.cyan).frame(width:36,height:36).background(.cyan.opacity(0.1),in:Circle())}};HStack(spacing:8){GoalBar(value:Double(answeredToday),target:20,tint:.mint);GoalBar(value:Double(studySecondsToday),target:2400,tint:.cyan)}}.padding(.horizontal,18).padding(.top,12)}
 private var topicBadge:some View{HStack(spacing:7){Image(systemName:"atom");Text("ХИМИЯ · КИСЛОТЫ").font(.caption.bold())}.foregroundStyle(.cyan).padding(.horizontal,12).padding(.vertical,7).background(.cyan.opacity(0.09),in:Capsule()).overlay(Capsule().stroke(.cyan.opacity(0.25)))}
 private var questionCard:some View{VStack(spacing:14){ZStack{Circle().fill(.cyan.opacity(0.08)).frame(width:66,height:66);Image(systemName:revealed ? "checkmark.seal.fill":"flask.fill").font(.title).foregroundStyle(revealed ? .mint:.cyan).shadow(color:.cyan.opacity(0.7),radius:9)};Text(revealed ? question.answer:question.prompt).font(.system(size:27,weight:.bold,design:.rounded)).foregroundStyle(.white).multilineTextAlignment(.center).minimumScaleFactor(0.75);Text(revealed ? "Нажми оценку ниже":"Нажми на карточку, чтобы перевернуть").font(.caption).foregroundStyle(.white.opacity(0.48))}.padding(.horizontal,18).padding(.vertical,22).frame(maxWidth:.infinity).frame(height:245).background(.black.opacity(0.20),in:RoundedRectangle(cornerRadius:28)).overlay(RoundedRectangle(cornerRadius:28).stroke(LinearGradient(colors:[.cyan.opacity(0.45),.purple.opacity(0.22)],startPoint:.topLeading,endPoint:.bottomTrailing),lineWidth:1)).rotation3DEffect(.degrees(advancing ? 180 : (revealed ? 360:0)),axis:(x:0,y:1,z:0)).animation(.spring(response:0.5,dampingFraction:0.78),value:revealed).onTapGesture{if question.kind == .reveal{revealed.toggle()}else if (question.kind == .singleChoice || question.kind == .multipleChoice) && checked{animateAdvanceAfterChoice()}else if question.kind == .multipleChoice && checked{animateAdvanceAfterChoice()}else if checked{revealed.toggle()}}}
 @ViewBuilder private var answerArea:some View{if question.kind == .reveal || question.kind == .pair{revealAnswer}else{choiceAnswer}}
 private var revealAnswer:some View{Group{if revealed{VStack(spacing:8){confidenceButton("ОТВЕТИЛ ЛЕГКО",.good,.mint);confidenceButton("СОМНЕВАЛСЯ",.hard,.yellow);confidenceButton("ПОВЕЗЛО — УГАДАЛ",.hard,.orange);confidenceButton("НАДО ПОВТОРЯТЬ",.again,.pink)}}else{Color.clear}}.frame(height:220)}
 private func confidenceButton(_ title:String,_ value:RecallRating,_ color:Color)->some View{Button{submit(value)}label:{HStack{Circle().fill(color).frame(width:8,height:8);Text(title).font(.subheadline.bold());Spacer();Image(systemName:"chevron.right")}.foregroundStyle(.white).padding(.horizontal,16).frame(height:46).background(color.opacity(0.10),in:RoundedRectangle(cornerRadius:15)).overlay(RoundedRectangle(cornerRadius:15).stroke(color.opacity(0.35)))}.buttonStyle(.plain)}
 private var choiceAnswer:some View{VStack(spacing:10){ForEach(Array(question.choices.prefix(6).enumerated()),id:\.offset){i,c in Button{if (question.kind == .singleChoice || question.kind == .multipleChoice) && checked{animateAdvanceAfterChoice()}else{choose(i)}}label:{HStack(spacing:12){Text(["A","B","C","D"][min(i,3)]).font(.caption.bold()).frame(width:30,height:30).background(choiceColor(i).opacity(0.18),in:Circle());Text(c).font(.body.weight(.semibold));Spacer();if checked && question.correctChoiceIndexes.contains(i){Image(systemName:"checkmark.circle.fill")}}.foregroundStyle(choiceColor(i)).padding(.horizontal,14).frame(minHeight:58).background(choiceColor(i).opacity(0.07),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(choiceColor(i).opacity(0.38)))}.buttonStyle(.plain).disabled(checked)};if question.kind == .multipleChoice && !checked{Button{checkAnswers()}label:{Text("ОТВЕТИТЬ").font(.headline).foregroundStyle(.white).frame(maxWidth:.infinity).frame(height:54).background(selection.isEmpty ? Color.white.opacity(0.08):Color.blue.opacity(0.8),in:RoundedRectangle(cornerRadius:18))}.disabled(selection.isEmpty)};if checked{Text(question.kind == .singleChoice ? "Правильный ответ подсвечен · нажми ещё раз, чтобы дальше" : "Правильные ответы подсвечены · нажми ещё раз, чтобы дальше").font(.caption).foregroundStyle(.mint);if revealed && question.kind != .singleChoice && question.kind != .multipleChoice{ratingButtons}}}}
 private func choiceColor(_ i:Int)->Color{if checked{return question.correctChoiceIndexes.contains(i) ? .mint : (selection.contains(i) ? .orange:.white)};return selection.contains(i) ? .cyan:.white}
 private func choose(_ i:Int){if question.kind == .singleChoice{selection=[i];checkAnswers()}else if selection.contains(i){selection.remove(i)}else{selection.insert(i)}}
 private func animateAdvanceAfterChoice(){guard !advancing else{return};withAnimation(.easeIn(duration:0.22)){advancing=true};DispatchQueue.main.asyncAfter(deadline:.now()+0.22){advanceAfterChoice();withAnimation(.easeOut(duration:0.22)){advancing=false}}}
 private func advanceAfterChoice(){countQuestionTime();answeredToday+=1;let ok=selection == question.correctChoiceIndexes;store.record(question:question,rating:ok ? .good:.again);if index+1<store.questions.count{index+=1;questionStartedAt=Date();activeStartedAt = scenePhase == .active ? Date():nil;activeQuestionSeconds=0;revealed=false;checked=false;selection=[]}else{finished=true}}
 private func checkAnswers(){withAnimation(.easeInOut(duration:0.2)){checked=true}}
 private var ratingButtons:some View{HStack(spacing:8){rating("НЕ ПОМНЮ",.again,.orange);rating("С ТРУДОМ",.hard,.yellow);rating("ЗНАЮ",.good,.mint)}}
 private func rating(_ title:String,_ value:RecallRating,_ color:Color)->some View{Button{submit(value)}label:{Text(title).font(.system(size:11,weight:.bold)).foregroundStyle(color).frame(maxWidth:.infinity).frame(height:44).background(color.opacity(0.10),in:RoundedRectangle(cornerRadius:14)).overlay(RoundedRectangle(cornerRadius:14).stroke(color.opacity(0.35)))}.buttonStyle(.plain)}
 private var resultView:some View{VStack(spacing:20){Spacer();ZStack{Circle().fill(.cyan.opacity(0.12)).frame(width:150,height:150);Image(systemName:"sparkles").font(.system(size:66)).foregroundStyle(.cyan).shadow(color:.cyan,radius:18)};Text("ВОПРОСЫ ЗАКОНЧИЛИСЬ").font(.largeTitle.bold()).foregroundStyle(.white);Text("Сегодня: \(answeredToday) вопросов · \(studySecondsToday/60) мин").font(.title3.bold()).foregroundStyle(.cyan);Button("ГОТОВО"){dismiss()}.buttonStyle(.borderedProminent).controlSize(.large);Spacer()}.padding()}
 private func toggle(_ i:Int){if question.kind == .singleChoice{selection=[i]}else if selection.contains(i){selection.remove(i)}else{selection.insert(i)}}
 private func submit(_ r:RecallRating){countQuestionTime();answeredToday+=1;store.record(question:question,rating:r);if r == .good{combo+=1;earnedXP+=10}else if r == .hard{earnedXP+=6}else{combo=0;earnedXP+=3};if index+1<store.questions.count{index+=1;questionStartedAt=Date();activeStartedAt = scenePhase == .active ? Date():nil;activeQuestionSeconds=0;revealed=false;checked=false;selection=[]}else{finished=true}}
 private func countQuestionTime(){var total=activeQuestionSeconds;if let start=activeStartedAt{total += Date().timeIntervalSince(start)};studySecondsToday += max(0,Int(total));activeStartedAt=nil;activeQuestionSeconds=0}
 private func handleScenePhase(_ phase:ScenePhase){switch phase{case .active: if activeStartedAt == nil{activeStartedAt=Date()};case .inactive,.background: if let start=activeStartedAt{activeQuestionSeconds += Date().timeIntervalSince(start);activeStartedAt=nil};@unknown default:break}}

}
private struct LearnDigitalBackground:View{var body:some View{ZStack{LinearGradient(colors:[Color(red:0.015,green:0.025,blue:0.08),Color(red:0.025,green:0.055,blue:0.14),Color(red:0.08,green:0.025,blue:0.16)],startPoint:.topLeading,endPoint:.bottomTrailing).ignoresSafeArea();Circle().fill(.cyan.opacity(0.10)).frame(width:280,height:280).blur(radius:70).offset(x:-150,y:-270);Circle().fill(.purple.opacity(0.12)).frame(width:300,height:300).blur(radius:80).offset(x:160,y:250)}}}
private struct DailyHUD:View{let icon:String;let value:String;let done:Bool;var body:some View{HStack(spacing:4){Image(systemName:done ? "checkmark.circle.fill":icon);Text(value).font(.caption.bold().monospacedDigit())}.foregroundStyle(done ? .mint:.white.opacity(0.86))}}
private struct GoalBar:View{let value:Double;let target:Double;let tint:Color;var body:some View{GeometryReader{g in ZStack(alignment:.leading){Capsule().fill(.white.opacity(0.08));Capsule().fill(tint).frame(width:g.size.width*min(value/target,1))}}.frame(height:5)}}
